version: '2'
services:
#docker-compose run biosamples-pipelines --service-ports
  biosamples-pipelines:
    build: .
    image: biosamples:latest
    links:
    - biosamples-webapps-api
    command:
    - java
    - -jar
    - pipelines-4.0.0-SNAPSHOT.jar
#    - --debug
    - --ncbi
    - --spring.aop.proxy-target-class=true
    #from https://github.com/google/guava/blob/master/guava/src/com/google/common/cache/CacheBuilderSpec.java
    - --spring.cache.guava.spec=maximumSize=500,expireAfterAccess=60s,recordStats=true
  biosamples-webapps-api:
    build: .
    image: biosamples:latest
    links:
    - solr
    - neo4j
    - mongo
    - rabbitmq
    command:
    - java
    - -jar
    - webapps-api-4.0.0-SNAPSHOT.war
#    - --debug
    - --spring.data.solr.host=http://solr:8983/solr
    - --spring.data.neo4j.uri=bolt://neo4j:7687
    - --spring.data.neo4j.username=neo4j
    - --spring.data.mongodb.host=mongo
    - --spring.rabbitmq.host=rabbitmq
    - --spring.rabbitmq.publisher-confirms=true
    - --spring.jackson.serialization-inclusion=non_null
    - --spring.data.rest.base-path=/api
    ports:
    - 8081:8080
  biosamples-agents-neo4j:
    build: .
    image: biosamples:latest
    links:
    - neo4j
    - rabbitmq
    command:
    - java
    - -jar
    - agents-neo4j-4.0.0-SNAPSHOT.jar
#    - --debug
    - --spring.rabbitmq.host=rabbitmq
    - --spring.rabbitmq.publisher-confirms=true
    - --spring.data.neo4j.uri=bolt://neo4j:7687
    - --spring.data.neo4j.username=neo4j
    restart: unless-stopped
  biosamples-agents-solr:
    build: .
    image: biosamples:latest
    links:
    - solr
    - rabbitmq
    command:
    - java
    - -jar
    - agents-solr-4.0.0-SNAPSHOT.jar
#    - --debug
    - --spring.rabbitmq.host=rabbitmq
    - --spring.rabbitmq.publisher-confirms=true
    - --spring.data.solr.host=http://solr:8983/solr
    restart: unless-stopped
  mongo:
    image: mongo:3.2
    volumes:
    - ./docker/mongo/conf:/data/configdb
    - mongo_data:/data/db
    ports:
    - 27017:27017
  rabbitmq:
    image: rabbitmq:3.6-management
    hostname: biosamples-rabbitmq
    ports:
    - 15672:15672
    volumes:
    - rabbitmq_data:/var/lib/rabbitmq/mnesia/rabbit@biosamples-rabbitmq
  neo4j:
    image: neo4j:3.0
    environment:
    - NEO4J_AUTH=none
    ports:
    - 7687:7687
    - 7474:7474
  solr:
    image: solr:6.3-alpine
    ports:
    - 8983:8983
    volumes:
    - ./docker/solr/docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d
    - solr_samples_data:/opt/solr/server/solr/mycores
    environment:
    - VERBOSE=yes
    - SOLR_HEAP=4g
    entrypoint:
    - docker-entrypoint.sh
    - solr-precreate
    - samples
networks:
  default:
    ipam:
      config:
      - subnet: 172.28.0.0/16
volumes:
  #get image sizes with `du -h /var/lib/docker/volumes/*_data` as docker user (root)
  solr_samples_data: null
  mongo_data: null
  rabbitmq_data: null