version: '2'
services:

  biosamples-webapps-core:
    build: .
    image: biosamples:latest
    links:
    - solr
    - mongo
    - rabbitmq
    volumes:
    - logs:/logs
    command:
    - java
    - -jar
    # - -agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=8000
    - webapps-core-4.0.0-SNAPSHOT.war
    environment:
    #AAP certificate
    - jwt.certificate=public.der
    - security.basic.path=
    - aap.domains.url=https://explore.api.aap.tsi.ebi.ac.uk
    - aap.token.url=https://explore.api.aap.tsi.ebi.ac.uk/auth
    #configure other services
    - spring.data.solr.host=http://solr:8983/solr
    - spring.data.mongodb.host=mongo
    - spring.rabbitmq.publisher-confirms=true
    - spring.rabbitmq.host=rabbitmq
    - spring.jackson.serialization-inclusion=non_null
    - spring.jackson.serialization.WRITE_NULL_MAP_VALUES=false
    - spring.jackson.serialization.indent_output=true
    #Configure root path to server from
    - server.servlet.context-path=/biosamples/beta
    - server.context-path=/biosamples/beta
    #Enable use behind a proxy with original urls
    - server.use-forward-headers=true
    #Improve logging
    - LOGGING_FILE=/logs/webapps-core.log
    - server.tomcat.accesslog.enabled=true
    - server.tomcat.accesslog.directory=/logs
    - server.tomcat.accesslog.prefix=webapps-core.access
    - server.tomcat.accesslog.pattern=%h %l %u %t "%r" %s %b (%D ms)
    #Enable gzip compression of responses
    - server.compression.enabled=true
    - server.compression.mime-types=application/json,application/hal+json,application/xml,text/html,application/javascript,text/css
    #Don't waste CPU compressing very small responses
    - server.compression.min-response-size=2048
    # Charset of HTTP requests and responses. Added to the "Content-Type" header if not set explicitly.
    - spring.http.encoding.charset=UTF-8
    # Enable http encoding support.
    - spring.http.encoding.enabled=true
    # Force the encoding to the configured charset on HTTP requests and responses.
    - spring.http.encoding.force=true
    - endpoints.shutdown.enabled=true
    - endpoints.shutdown.sensitive=false
    ports:
    - 8081:8080
    - 9090:9090
    - 8000:8000
    
  biosamples-webapps-sampletab:
    image: biosamples:latest
    links:
    - biosamples-webapps-core
    volumes:
    - logs:/logs
    command:
    - java
    - -jar
    - webapps-sampletab-4.0.0-SNAPSHOT.war
    environment:
    - BIOSAMPLES_CLIENT_URI=http://biosamples-webapps-core:8080/biosamples/beta
    - SERVER_SERVLET_CONTEXT-PATH=/biosamples/beta/sampletab
    - SERVER_CONTEXT-PATH=/biosamples/beta/sampletab
    - MANAGEMENT_SECURITY_ENABLED=false
    - LOGGING_FILE=/logs/webapps-sampletab.log
    - SERVER_TOMCAT_ACCESSLOG_ENABLED=true
    - SERVER_TOMCAT_ACCESSLOG_DIRECTORY=/logs
    - SERVER_TOMCAT_ACCESSLOG_PREFIX=webapps-sampletab.access
    - SERVER_TOMCAT_ACCESSLOG_PATTERN=%h %l %u %t "%r" %s %b (%D ms)
    # Charset of HTTP requests and responses. Added to the "Content-Type" header if not set explicitly.
    - SPRING_HTTP_ENCODING_CHARSET=UTF-8
    # Enable http encoding support.
    - SPRING_HTTP_ENCODING_ENABLED=true
    # Force the encoding to the configured charset on HTTP requests and responses.
    - spring.http.encoding.force=true
    - ENDPOINTS_SHUTDOWN_ENABLED=true
    - ENDPOINTS_SHUTDOWN_SENSITIVE=false
    # Provide information about database
    - spring.datasource.accession.url=override_in_docker-compose.override.yml
    - spring.datasource.accession.username=override_in_docker-compose.override.yml
    - spring.datasource.accession.password=override_in_docker-compose.override.yml
    - spring.datasource.accession.driver-class-name=override_in_docker-compose.override.yml
    # Provide AAP infos
    - BIOSAMPLES_CLIENT_AAP_USERNAME=override_in_docker-compose.override.yml
    - BIOSAMPLES_CLIENT_AAP_PASSWORD=override_in_docker-compose.override.yml
    - spring.data.mongodb.host=mongo
    ports:
    - 8082:8080
  
  biosamples-webapps-legacyxml:
    image: biosamples:latest
    links:
    - biosamples-webapps-core
    volumes:
    - logs:/logs
    command:
    - java
    - -jar
    - webapps-legacyxml-4.0.0-SNAPSHOT.war
    environment:
    - BIOSAMPLES_REDIRECT_CONTEXT=http://biosamples-webapps-core:8080/biosamples/beta
    - BIOSAMPLES_CLIENT_URI=http://biosamples-webapps-core:8080/biosamples/beta
    - SERVER_SERVLET_CONTEXT-PATH=/biosamples/beta/xml
    - SERVER_CONTEXT-PATH=/biosamples/beta/xml
    - SPRING_JACKSON_SERIALIZATION_INDENT_OUTPUT=true
    - LOGGING_FILE=/logs/webapps-legacyxml.log
    - SERVER_TOMCAT_ACCESSLOG_ENABLED=true
    - SERVER_TOMCAT_ACCESSLOG_DIRECTORY=/logs
    - SERVER_TOMCAT_ACCESSLOG_PREFIX=webapps-legacyxml.access
    - SERVER_TOMCAT_ACCESSLOG_PATTERN=%h %l %u %t "%r" %s %b (%D ms)
    - ENDPOINTS_SHUTDOWN_ENABLED=true
    - ENDPOINTS_SHUTDOWN_SENSITIVE=false
    # Provide AAP infos
    - BIOSAMPLES_CLIENT_AAP_USERNAME=override_in_docker-compose.override.yml
    - BIOSAMPLES_CLIENT_AAP_PASSWORD=override_in_docker-compose.override.yml
    ports:
    - 8083:8080

  biosamples-webapps-legacyjson:
    image: biosamples:latest
    links:
      - biosamples-webapps-core
    volumes:
      - logs:/logs
    command:
      - java
      - -jar
      - webapps-legacyjson-4.0.0-SNAPSHOT.war
    environment:
      - BIOSAMPLES_CLIENT_URI=http://biosamples-webapps-core:8080/biosamples/beta
      - SERVER_SERVLET_CONTEXT-PATH=/biosamples/beta/api
      - SERVER_CONTEXT-PATH=/biosamples/beta/api
      - SPRING_JACKSON_SERIALIZATION_INDENT_OUTPUT=true
      - LOGGING_FILE=/logs/webapps-legacyjson.log
      - SERVER_TOMCAT_ACCESSLOG_ENABLED=true
      - SERVER_TOMCAT_ACCESSLOG_DIRECTORY=/logs
      - SERVER_TOMCAT_ACCESSLOG_PREFIX=webapps-legacyjson.access
      - SERVER_TOMCAT_ACCESSLOG_PATTERN=%h %l %u %t "%r" %s %b (%D ms)
      - ENDPOINTS_SHUTDOWN_ENABLED=true
      - ENDPOINTS_SHUTDOWN_SENSITIVE=false
      # Provide AAP infos
      - BIOSAMPLES_CLIENT_AAP_USERNAME=override_in_docker-compose.override.yml
      - BIOSAMPLES_CLIENT_AAP_PASSWORD=override_in_docker-compose.override.yml
    ports:
      - 8084:8080

  biosamples-agents-solr:
    image: biosamples:latest
    links:
    - solr
    - rabbitmq
    volumes:
    - logs:/logs
    command:
    - java
    - -jar
    - agents-solr-4.0.0-SNAPSHOT.jar
    environment:
    - SPRING_RABBITMQ_PUBLISHER-CONFIRMS=true
    - SPRING_RABBITMQ_PUBLISHER-RETURNS=true
    - SPRING_RABBITMQ_LISTENER_CONCURRENCY=1000
    - SPRING_RABBITMQ_LISTENER_MAX-CONCURRENCY=1000
    - BIOSAMPLES_AGENT_SOLR_QUEUESIZE=1000
    - BIOSAMPLES_AGENT_SOLR_QUEUETIME=10000
    - SPRING_DATA_SOLR_HOST=http://solr:8983/solr
    - SPRING_RABBITMQ_HOST=rabbitmq
    - BIOSAMPLES_AGENT_SOLR_STAYALIVE=true
    - LOGGING_FILE=/logs/agents-solr.log
       

  biosamples-pipelines-ena:
    image: biosamples:latest
    volumes:
    - logs:/logs
    links:
    - biosamples-webapps-core
    command:
    - java
    - -jar
    - pipelines-ena-4.0.0-SNAPSHOT.jar
    environment:
    - BIOSAMPLES_CLIENT_URI=http://biosamples-webapps-core:8080/biosamples/beta
    - LOGGING_FILE=/logs/pipelines-ena.log
    
  biosamples-pipelines-ncbi:
    image: biosamples-pipelines-ncbi:latest
    build:
      context: docker/pipelines-ncbi/
    volumes:
    - logs:/logs
    links:
    - biosamples-webapps-core
    environment:
    - BIOSAMPLES_CLIENT_URI=http://biosamples-webapps-core:8080/biosamples/beta
    - LOGGING_FILE=/logs/pipelines-ncbi.log
    - SPRING_CACHE_GUAVA_SPEC=maximumSize=500,expireAfterAccess=60s,recordStats=true
    
  biosamples-pipelines-accession:
    image: biosamples:latest
    volumes:
    - logs:/logs
    links:
    - biosamples-webapps-core
    command:
    - java
    - -jar
    - pipelines-accession-4.0.0-SNAPSHOT.jar
    environment:
    - BIOSAMPLES_CLIENT_URI=http://biosamples-webapps-core:8080/biosamples/beta
    - LOGGING_FILE=/logs/pipelines-accession.log      
    
  biosamples-pipelines-sampletab:
    image: biosamples:latest
    volumes:
    - logs:/logs
    links:
    - biosamples-webapps-core
    command:
    - java
    - -jar
    - pipelines-sampletab-4.0.0-SNAPSHOT.jar
    environment:
    - BIOSAMPLES_SAMPLETAB_URI=http://biosamples-webapps-sampletab:8080/biosamples/beta/sampletab/v4
    - LOGGING_FILE=/logs/pipelines-sampletab.log  
    
  biosamples-pipelines-curation:
    volumes:
    - logs:/logs
    image: biosamples:latest
    links:
    - biosamples-webapps-core
    command:
    - java
    - -jar
    - pipelines-curation-4.0.0-SNAPSHOT.jar
    environment:
    - BIOSAMPLES_CLIENT_URI=http://biosamples-webapps-core:8080/biosamples/beta
    - LOGGING_FILE=/logs/pipelines-curation.log
       
    
  biosamples-integration:
    volumes:
    - logs:/logs
    image: biosamples:latest
    links:
    - biosamples-webapps-core
    - biosamples-webapps-sampletab
    - biosamples-webapps-legacyxml
    - biosamples-webapps-legacyjson
    command:
    - java
    - -jar
    - integration-4.0.0-SNAPSHOT.jar
    environment:
    - BIOSAMPLES_CLIENT_URI=http://biosamples-webapps-core:8080/biosamples/beta
    - BIOSAMPLES_SUBMISSIONURI=http://biosamples-webapps-sampletab:8080/biosamples/beta/sampletab
    - BIOSAMPLES_SUBMISSIONURI_SAMPLETAB=http://biosamples-webapps-sampletab:8080/biosamples/beta/sampletab
    - BIOSAMPLES_LEGACYXML=http://biosamples-webapps-legacyxml:8080/biosamples/beta/xml
    - BIOSAMPLES_LEGACYXML_URI=http://biosamples-webapps-legacyxml:8080/biosamples/beta/xml
    - BIOSAMPLES_LEGACYJSON_URI=http://biosamples-webapps-legacyjson:8080/biosamples/beta/api
    - LOGGING_FILE=/logs/integration.log
    # Provide AAP infos
    - BIOSAMPLES_CLIENT_AAP_USERNAME=override_in_docker-compose.override.yml
    - BIOSAMPLES_CLIENT_AAP_PASSWORD=override_in_docker-compose.override.yml
    - BIOSAMPLES_LEGACYAPIKEY=override_in_docker-compose.override.yml
       
  mongo:
    image: mongo:3.2
    volumes:
    - mongo_data:/data/db
    ports:
    - 27017:27017
    
  rabbitmq:
    image: rabbitmq:3.6-management-alpine
    hostname: biosamples-rabbitmq
    ports:
    - 5672:5672
    - 15672:15672
    volumes:
    - rabbitmq_data:/var/lib/rabbitmq/mnesia
    
    
  solr:
    image: solr:6.6-alpine
    ports:
    - 8983:8983
    volumes:
    - solr_data:/opt/solr/server/solr/mycores
    environment:
    - VERBOSE=yes
    - SOLR_HEAP=2g
    entrypoint:
    - docker-entrypoint.sh
    - solr-precreate
    - samples
    
volumes:
  solr_data: null
  mongo_data: null
  rabbitmq_data: null
  logs: null
